/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiKeyOut {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "last_used_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<Option<String>>,
    #[serde(rename = "expires_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<String>>,
    #[serde(rename = "is_active")]
    pub is_active: bool,
}

impl ApiKeyOut {
    pub fn new(id: i32, name: String, prefix: String, created_at: String, is_active: bool) -> ApiKeyOut {
        ApiKeyOut {
            id,
            name,
            prefix,
            created_at,
            last_used_at: None,
            expires_at: None,
            is_active,
        }
    }
}

