/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteEpicsIn {
    #[serde(rename = "epic_ids")]
    pub epic_ids: Vec<String>,
}

impl BatchDeleteEpicsIn {
    pub fn new(epic_ids: Vec<String>) -> BatchDeleteEpicsIn {
        BatchDeleteEpicsIn { epic_ids }
    }
}
