/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteSchedulesIn {
    #[serde(rename = "schedule_ids")]
    pub schedule_ids: Vec<String>,
}

impl BatchDeleteSchedulesIn {
    pub fn new(schedule_ids: Vec<String>) -> BatchDeleteSchedulesIn {
        BatchDeleteSchedulesIn {
            schedule_ids,
        }
    }
}

