/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteCheckpointsIn {
    #[serde(
        rename = "thread_ids",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub thread_ids: Option<Option<Vec<String>>>,
    #[serde(
        rename = "checkpoint_ids",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub checkpoint_ids: Option<Option<Vec<String>>>,
}

impl BatchDeleteCheckpointsIn {
    pub fn new() -> BatchDeleteCheckpointsIn {
        BatchDeleteCheckpointsIn {
            thread_ids: None,
            checkpoint_ids: None,
        }
    }
}
