/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteProceduresIn {
    #[serde(rename = "ids")]
    pub ids: Vec<String>,
}

impl BatchDeleteProceduresIn {
    pub fn new(ids: Vec<String>) -> BatchDeleteProceduresIn {
        BatchDeleteProceduresIn { ids }
    }
}
