/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteTasksIn {
    #[serde(rename = "task_ids")]
    pub task_ids: Vec<String>,
}

impl BatchDeleteTasksIn {
    pub fn new(task_ids: Vec<String>) -> BatchDeleteTasksIn {
        BatchDeleteTasksIn { task_ids }
    }
}
