/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeleteExecutionsIn {
    #[serde(rename = "execution_ids")]
    pub execution_ids: Vec<String>,
}

impl BatchDeleteExecutionsIn {
    pub fn new(execution_ids: Vec<String>) -> BatchDeleteExecutionsIn {
        BatchDeleteExecutionsIn { execution_ids }
    }
}
