/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilitiesInfo {
    #[serde(rename = "runtimes")]
    pub runtimes: std::collections::HashMap<String, models::RuntimeInfo>,
    #[serde(rename = "shell_tools")]
    pub shell_tools: std::collections::HashMap<String, models::ShellToolInfo>,
    #[serde(rename = "network")]
    pub network: Box<models::NetworkInfo>,
}

impl CapabilitiesInfo {
    pub fn new(
        runtimes: std::collections::HashMap<String, models::RuntimeInfo>,
        shell_tools: std::collections::HashMap<String, models::ShellToolInfo>,
        network: models::NetworkInfo,
    ) -> CapabilitiesInfo {
        CapabilitiesInfo {
            runtimes,
            shell_tools,
            network: Box::new(network),
        }
    }
}
