/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatMessageIn {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(
        rename = "trigger_node_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_node_id: Option<Option<String>>,
}

impl ChatMessageIn {
    pub fn new(text: String) -> ChatMessageIn {
        ChatMessageIn {
            text,
            trigger_node_id: None,
        }
    }
}
