/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatMessageOut {
    #[serde(rename = "execution_id")]
    pub execution_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "response")]
    pub response: String,
}

impl ChatMessageOut {
    pub fn new(execution_id: String, status: String, response: String) -> ChatMessageOut {
        ChatMessageOut {
            execution_id,
            status,
            response,
        }
    }
}
