/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentConfigData {
    #[serde(rename = "system_prompt", skip_serializing_if = "Option::is_none")]
    pub system_prompt: Option<String>,
    #[serde(rename = "extra_config", skip_serializing_if = "Option::is_none")]
    pub extra_config: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(
        rename = "llm_credential_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub llm_credential_id: Option<Option<i32>>,
    #[serde(rename = "model_name", skip_serializing_if = "Option::is_none")]
    pub model_name: Option<String>,
    #[serde(
        rename = "temperature",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub temperature: Option<Option<f64>>,
    #[serde(
        rename = "max_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_tokens: Option<Option<i32>>,
    #[serde(
        rename = "frequency_penalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub frequency_penalty: Option<Option<f64>>,
    #[serde(
        rename = "presence_penalty",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub presence_penalty: Option<Option<f64>>,
    #[serde(
        rename = "top_p",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub top_p: Option<Option<f64>>,
    #[serde(
        rename = "timeout",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout: Option<Option<i32>>,
    #[serde(
        rename = "max_retries",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_retries: Option<Option<i32>>,
    #[serde(
        rename = "response_format",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub response_format: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(
        rename = "llm_model_config_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub llm_model_config_id: Option<Option<i32>>,
    #[serde(
        rename = "credential_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub credential_id: Option<Option<i32>>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "trigger_config", skip_serializing_if = "Option::is_none")]
    pub trigger_config: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl ComponentConfigData {
    pub fn new() -> ComponentConfigData {
        ComponentConfigData {
            system_prompt: None,
            extra_config: None,
            llm_credential_id: None,
            model_name: None,
            temperature: None,
            max_tokens: None,
            frequency_penalty: None,
            presence_penalty: None,
            top_p: None,
            timeout: None,
            max_retries: None,
            response_format: None,
            llm_model_config_id: None,
            credential_id: None,
            is_active: None,
            priority: None,
            trigger_config: None,
        }
    }
}
