/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialOut {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "credential_type")]
    pub credential_type: CredentialType,
    #[serde(rename = "detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub detail: Option<Option<Box<models::Detail>>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl CredentialOut {
    pub fn new(id: i32, name: String, credential_type: CredentialType, created_at: String, updated_at: String) -> CredentialOut {
        CredentialOut {
            id,
            name,
            credential_type,
            detail: None,
            created_at,
            updated_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CredentialType {
    #[serde(rename = "git")]
    Git,
    #[serde(rename = "llm")]
    Llm,
    #[serde(rename = "gateway")]
    Gateway,
    #[serde(rename = "tool")]
    Tool,
}

impl Default for CredentialType {
    fn default() -> CredentialType {
        Self::Git
    }
}

