/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialTestOut {
    #[serde(rename = "ok")]
    pub ok: bool,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(rename = "detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub detail: Option<Option<Box<models::Detail>>>,
}

impl CredentialTestOut {
    pub fn new(ok: bool) -> CredentialTestOut {
        CredentialTestOut {
            ok,
            error: None,
            detail: None,
        }
    }
}

