/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CredentialIn {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "credential_type")]
    pub credential_type: CredentialType,
    #[serde(
        rename = "detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub detail: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl CredentialIn {
    pub fn new(name: String, credential_type: CredentialType) -> CredentialIn {
        CredentialIn {
            name,
            credential_type,
            detail: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CredentialType {
    #[serde(rename = "git")]
    Git,
    #[serde(rename = "llm")]
    Llm,
    #[serde(rename = "gateway")]
    Gateway,
    #[serde(rename = "tool")]
    Tool,
}

impl Default for CredentialType {
    fn default() -> CredentialType {
        Self::Git
    }
}
