/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EdgeOut {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "source_node_id")]
    pub source_node_id: String,
    #[serde(rename = "target_node_id")]
    pub target_node_id: String,
    #[serde(rename = "edge_type")]
    pub edge_type: EdgeType,
    #[serde(rename = "edge_label", skip_serializing_if = "Option::is_none")]
    pub edge_label: Option<EdgeLabel>,
    #[serde(
        rename = "condition_mapping",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub condition_mapping: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "condition_value", skip_serializing_if = "Option::is_none")]
    pub condition_value: Option<String>,
    #[serde(rename = "priority")]
    pub priority: i32,
}

impl EdgeOut {
    pub fn new(
        id: i32,
        source_node_id: String,
        target_node_id: String,
        edge_type: EdgeType,
        priority: i32,
    ) -> EdgeOut {
        EdgeOut {
            id,
            source_node_id,
            target_node_id,
            edge_type,
            edge_label: None,
            condition_mapping: None,
            condition_value: None,
            priority,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EdgeType {
    #[serde(rename = "direct")]
    Direct,
    #[serde(rename = "conditional")]
    Conditional,
}

impl Default for EdgeType {
    fn default() -> EdgeType {
        Self::Direct
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EdgeLabel {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "llm")]
    Llm,
    #[serde(rename = "tool")]
    Tool,
    #[serde(rename = "output_parser")]
    OutputParser,
    #[serde(rename = "loop_body")]
    LoopBody,
    #[serde(rename = "loop_return")]
    LoopReturn,
    #[serde(rename = "skill")]
    Skill,
}

impl Default for EdgeLabel {
    fn default() -> EdgeLabel {
        Self::Empty
    }
}
