/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnvironmentInfo {
    #[serde(rename = "os")]
    pub os: String,
    #[serde(rename = "arch")]
    pub arch: String,
    #[serde(rename = "container", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub container: Option<Option<String>>,
    #[serde(rename = "bwrap_available")]
    pub bwrap_available: bool,
    #[serde(rename = "rootfs_ready")]
    pub rootfs_ready: bool,
    #[serde(rename = "sandbox_mode")]
    pub sandbox_mode: String,
    #[serde(rename = "capabilities")]
    pub capabilities: Box<models::CapabilitiesInfo>,
    #[serde(rename = "tier1_met")]
    pub tier1_met: bool,
    #[serde(rename = "tier2_warnings")]
    pub tier2_warnings: Vec<String>,
    #[serde(rename = "gate")]
    pub gate: Box<models::GateResult>,
}

impl EnvironmentInfo {
    pub fn new(os: String, arch: String, bwrap_available: bool, rootfs_ready: bool, sandbox_mode: String, capabilities: models::CapabilitiesInfo, tier1_met: bool, tier2_warnings: Vec<String>, gate: models::GateResult) -> EnvironmentInfo {
        EnvironmentInfo {
            os,
            arch,
            container: None,
            bwrap_available,
            rootfs_ready,
            sandbox_mode,
            capabilities: Box::new(capabilities),
            tier1_met,
            tier2_warnings,
            gate: Box::new(gate),
        }
    }
}

