/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EpicOut {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(
        rename = "created_by_node_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_by_node_id: Option<Option<String>>,
    #[serde(
        rename = "workflow_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub workflow_id: Option<Option<i32>>,
    #[serde(
        rename = "user_profile_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_profile_id: Option<Option<i32>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(
        rename = "budget_tokens",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub budget_tokens: Option<Option<i32>>,
    #[serde(
        rename = "budget_usd",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub budget_usd: Option<Option<f64>>,
    #[serde(rename = "spent_tokens", skip_serializing_if = "Option::is_none")]
    pub spent_tokens: Option<i32>,
    #[serde(rename = "spent_usd", skip_serializing_if = "Option::is_none")]
    pub spent_usd: Option<f64>,
    #[serde(
        rename = "agent_overhead_tokens",
        skip_serializing_if = "Option::is_none"
    )]
    pub agent_overhead_tokens: Option<i32>,
    #[serde(rename = "agent_overhead_usd", skip_serializing_if = "Option::is_none")]
    pub agent_overhead_usd: Option<f64>,
    #[serde(rename = "total_tasks", skip_serializing_if = "Option::is_none")]
    pub total_tasks: Option<i32>,
    #[serde(rename = "completed_tasks", skip_serializing_if = "Option::is_none")]
    pub completed_tasks: Option<i32>,
    #[serde(rename = "failed_tasks", skip_serializing_if = "Option::is_none")]
    pub failed_tasks: Option<i32>,
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<String>>,
    #[serde(
        rename = "updated_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated_at: Option<Option<String>>,
    #[serde(
        rename = "completed_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub completed_at: Option<Option<String>>,
    #[serde(
        rename = "result_summary",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub result_summary: Option<Option<String>>,
}

impl EpicOut {
    pub fn new(id: String, title: String) -> EpicOut {
        EpicOut {
            id,
            title,
            description: None,
            tags: None,
            created_by_node_id: None,
            workflow_id: None,
            user_profile_id: None,
            status: None,
            priority: None,
            budget_tokens: None,
            budget_usd: None,
            spent_tokens: None,
            spent_usd: None,
            agent_overhead_tokens: None,
            agent_overhead_usd: None,
            total_tasks: None,
            completed_tasks: None,
            failed_tasks: None,
            created_at: None,
            updated_at: None,
            completed_at: None,
            result_summary: None,
        }
    }
}
