/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionOut {
    #[serde(rename = "execution_id")]
    pub execution_id: String,
    #[serde(rename = "workflow_slug")]
    pub workflow_slug: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "started_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<Option<String>>,
    #[serde(rename = "completed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<String>>,
    #[serde(rename = "total_tokens", skip_serializing_if = "Option::is_none")]
    pub total_tokens: Option<i32>,
    #[serde(rename = "total_cost_usd", skip_serializing_if = "Option::is_none")]
    pub total_cost_usd: Option<f64>,
    #[serde(rename = "llm_calls", skip_serializing_if = "Option::is_none")]
    pub llm_calls: Option<i32>,
}

impl ExecutionOut {
    pub fn new(execution_id: String, workflow_slug: String, status: String) -> ExecutionOut {
        ExecutionOut {
            execution_id,
            workflow_slug,
            status,
            error_message: None,
            started_at: None,
            completed_at: None,
            total_tokens: None,
            total_cost_usd: None,
            llm_calls: None,
        }
    }
}

