/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GatewayInboundMessage : Inbound message from gateway webhook.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayInboundMessage {
    #[serde(rename = "route")]
    pub route: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "credential_id")]
    pub credential_id: String,
    #[serde(rename = "source")]
    pub source: Box<models::InboundSource>,
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::InboundAttachment>>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(
        rename = "extra_data",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub extra_data: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl GatewayInboundMessage {
    /// Inbound message from gateway webhook.
    pub fn new(
        route: std::collections::HashMap<String, serde_json::Value>,
        credential_id: String,
        source: models::InboundSource,
        text: String,
        timestamp: String,
    ) -> GatewayInboundMessage {
        GatewayInboundMessage {
            route,
            credential_id,
            source: Box::new(source),
            text,
            attachments: None,
            timestamp,
            extra_data: None,
        }
    }
}
