/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboundAttachment : Attachment in inbound message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboundAttachment {
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "size_bytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i32>,
    #[serde(rename = "download_url", skip_serializing_if = "Option::is_none")]
    pub download_url: Option<String>,
}

impl InboundAttachment {
    /// Attachment in inbound message.
    pub fn new(filename: String, mime_type: String) -> InboundAttachment {
        InboundAttachment {
            filename,
            mime_type,
            size_bytes: None,
            download_url: None,
        }
    }
}

