/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InboundSource : Source information for inbound message.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InboundSource {
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "chat_id")]
    pub chat_id: String,
    #[serde(rename = "message_id", skip_serializing_if = "Option::is_none")]
    pub message_id: Option<String>,
    #[serde(rename = "reply_to_message_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reply_to_message_id: Option<Option<String>>,
    #[serde(rename = "from", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub from: Option<Option<Box<models::UserInfo>>>,
}

impl InboundSource {
    /// Source information for inbound message.
    pub fn new(protocol: String, chat_id: String) -> InboundSource {
        InboundSource {
            protocol,
            chat_id,
            message_id: None,
            reply_to_message_id: None,
            from: None,
        }
    }
}

