/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManualExecuteIn {
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(
        rename = "trigger_node_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_node_id: Option<Option<String>>,
}

impl ManualExecuteIn {
    pub fn new() -> ManualExecuteIn {
        ManualExecuteIn {
            text: None,
            trigger_node_id: None,
        }
    }
}
