/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MfaStatusResponse {
    #[serde(rename = "mfa_enabled")]
    pub mfa_enabled: bool,
}

impl MfaStatusResponse {
    pub fn new(mfa_enabled: bool) -> MfaStatusResponse {
        MfaStatusResponse {
            mfa_enabled,
        }
    }
}

