/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MfaSetupResponse {
    #[serde(rename = "secret")]
    pub secret: String,
    #[serde(rename = "provisioning_uri")]
    pub provisioning_uri: String,
}

impl MfaSetupResponse {
    pub fn new(secret: String, provisioning_uri: String) -> MfaSetupResponse {
        MfaSetupResponse {
            secret,
            provisioning_uri,
        }
    }
}
