/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MfaLoginVerifyRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "code")]
    pub code: String,
}

impl MfaLoginVerifyRequest {
    pub fn new(username: String, code: String) -> MfaLoginVerifyRequest {
        MfaLoginVerifyRequest {
            username,
            code,
        }
    }
}

