/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkInfo {
    #[serde(rename = "dns")]
    pub dns: bool,
    #[serde(rename = "http")]
    pub http: bool,
}

impl NetworkInfo {
    pub fn new(dns: bool, http: bool) -> NetworkInfo {
        NetworkInfo { dns, http }
    }
}
