/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeUpdate {
    #[serde(rename = "node_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<Option<String>>,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "component_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub component_type: Option<Option<ComponentType>>,
    #[serde(rename = "is_entry_point", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_entry_point: Option<Option<bool>>,
    #[serde(rename = "interrupt_before", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interrupt_before: Option<Option<bool>>,
    #[serde(rename = "interrupt_after", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interrupt_after: Option<Option<bool>>,
    #[serde(rename = "position_x", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub position_x: Option<Option<i32>>,
    #[serde(rename = "position_y", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub position_y: Option<Option<i32>>,
    #[serde(rename = "config", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub config: Option<Option<Box<models::ComponentConfigData>>>,
    #[serde(rename = "subworkflow_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subworkflow_id: Option<Option<i32>>,
    #[serde(rename = "code_block_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code_block_id: Option<Option<i32>>,
}

impl NodeUpdate {
    pub fn new() -> NodeUpdate {
        NodeUpdate {
            node_id: None,
            label: None,
            component_type: None,
            is_entry_point: None,
            interrupt_before: None,
            interrupt_after: None,
            position_x: None,
            position_y: None,
            config: None,
            subworkflow_id: None,
            code_block_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComponentType {
    #[serde(rename = "categorizer")]
    Categorizer,
    #[serde(rename = "router")]
    Router,
    #[serde(rename = "extractor")]
    Extractor,
    #[serde(rename = "ai_model")]
    AiModel,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "deep_agent")]
    DeepAgent,
    #[serde(rename = "switch")]
    Switch,
    #[serde(rename = "run_command")]
    RunCommand,
    #[serde(rename = "get_totp_code")]
    GetTotpCode,
    #[serde(rename = "platform_api")]
    PlatformApi,
    #[serde(rename = "whoami")]
    Whoami,
    #[serde(rename = "epic_tools")]
    EpicTools,
    #[serde(rename = "task_tools")]
    TaskTools,
    #[serde(rename = "spawn_and_await")]
    SpawnAndAwait,
    #[serde(rename = "workflow_create")]
    WorkflowCreate,
    #[serde(rename = "workflow_discover")]
    WorkflowDiscover,
    #[serde(rename = "scheduler_tools")]
    SchedulerTools,
    #[serde(rename = "system_health")]
    SystemHealth,
    #[serde(rename = "human_confirmation")]
    HumanConfirmation,
    #[serde(rename = "workflow")]
    Workflow,
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "code_execute")]
    CodeExecute,
    #[serde(rename = "loop")]
    Loop,
    #[serde(rename = "wait")]
    Wait,
    #[serde(rename = "merge")]
    Merge,
    #[serde(rename = "filter")]
    Filter,
    #[serde(rename = "error_handler")]
    ErrorHandler,
    #[serde(rename = "output_parser")]
    OutputParser,
    #[serde(rename = "memory_read")]
    MemoryRead,
    #[serde(rename = "memory_write")]
    MemoryWrite,
    #[serde(rename = "identify_user")]
    IdentifyUser,
    #[serde(rename = "trigger_telegram")]
    TriggerTelegram,
    #[serde(rename = "trigger_schedule")]
    TriggerSchedule,
    #[serde(rename = "trigger_manual")]
    TriggerManual,
    #[serde(rename = "trigger_workflow")]
    TriggerWorkflow,
    #[serde(rename = "trigger_error")]
    TriggerError,
    #[serde(rename = "trigger_chat")]
    TriggerChat,
    #[serde(rename = "skill")]
    Skill,
}

impl Default for ComponentType {
    fn default() -> ComponentType {
        Self::Categorizer
    }
}

