/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeOut {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "node_id")]
    pub node_id: String,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "component_type")]
    pub component_type: ComponentType,
    #[serde(rename = "is_entry_point")]
    pub is_entry_point: bool,
    #[serde(rename = "interrupt_before")]
    pub interrupt_before: bool,
    #[serde(rename = "interrupt_after")]
    pub interrupt_after: bool,
    #[serde(rename = "position_x")]
    pub position_x: i32,
    #[serde(rename = "position_y")]
    pub position_y: i32,
    #[serde(rename = "config")]
    pub config: Box<models::ComponentConfigData>,
    #[serde(rename = "subworkflow_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subworkflow_id: Option<Option<i32>>,
    #[serde(rename = "code_block_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code_block_id: Option<Option<i32>>,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "schedule_job", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub schedule_job: Option<Option<Box<models::ScheduleJobInfo>>>,
}

impl NodeOut {
    pub fn new(id: i32, node_id: String, component_type: ComponentType, is_entry_point: bool, interrupt_before: bool, interrupt_after: bool, position_x: i32, position_y: i32, config: models::ComponentConfigData, updated_at: String) -> NodeOut {
        NodeOut {
            id,
            node_id,
            label: None,
            component_type,
            is_entry_point,
            interrupt_before,
            interrupt_after,
            position_x,
            position_y,
            config: Box::new(config),
            subworkflow_id: None,
            code_block_id: None,
            updated_at,
            schedule_job: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ComponentType {
    #[serde(rename = "categorizer")]
    Categorizer,
    #[serde(rename = "router")]
    Router,
    #[serde(rename = "extractor")]
    Extractor,
    #[serde(rename = "ai_model")]
    AiModel,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "deep_agent")]
    DeepAgent,
    #[serde(rename = "switch")]
    Switch,
    #[serde(rename = "run_command")]
    RunCommand,
    #[serde(rename = "get_totp_code")]
    GetTotpCode,
    #[serde(rename = "platform_api")]
    PlatformApi,
    #[serde(rename = "whoami")]
    Whoami,
    #[serde(rename = "epic_tools")]
    EpicTools,
    #[serde(rename = "task_tools")]
    TaskTools,
    #[serde(rename = "spawn_and_await")]
    SpawnAndAwait,
    #[serde(rename = "workflow_create")]
    WorkflowCreate,
    #[serde(rename = "workflow_discover")]
    WorkflowDiscover,
    #[serde(rename = "scheduler_tools")]
    SchedulerTools,
    #[serde(rename = "system_health")]
    SystemHealth,
    #[serde(rename = "human_confirmation")]
    HumanConfirmation,
    #[serde(rename = "workflow")]
    Workflow,
    #[serde(rename = "code")]
    Code,
    #[serde(rename = "code_execute")]
    CodeExecute,
    #[serde(rename = "loop")]
    Loop,
    #[serde(rename = "wait")]
    Wait,
    #[serde(rename = "merge")]
    Merge,
    #[serde(rename = "filter")]
    Filter,
    #[serde(rename = "error_handler")]
    ErrorHandler,
    #[serde(rename = "output_parser")]
    OutputParser,
    #[serde(rename = "memory_read")]
    MemoryRead,
    #[serde(rename = "memory_write")]
    MemoryWrite,
    #[serde(rename = "identify_user")]
    IdentifyUser,
    #[serde(rename = "trigger_telegram")]
    TriggerTelegram,
    #[serde(rename = "trigger_schedule")]
    TriggerSchedule,
    #[serde(rename = "trigger_manual")]
    TriggerManual,
    #[serde(rename = "trigger_workflow")]
    TriggerWorkflow,
    #[serde(rename = "trigger_error")]
    TriggerError,
    #[serde(rename = "trigger_chat")]
    TriggerChat,
    #[serde(rename = "skill")]
    Skill,
}

impl Default for ComponentType {
    fn default() -> ComponentType {
        Self::Categorizer
    }
}

