/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PlatformConfigOut : Safe-to-expose conf.json values.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformConfigOut {
    #[serde(rename = "pipelit_dir")]
    pub pipelit_dir: String,
    #[serde(rename = "sandbox_mode")]
    pub sandbox_mode: String,
    #[serde(rename = "database_url")]
    pub database_url: String,
    #[serde(rename = "redis_url")]
    pub redis_url: String,
    #[serde(rename = "log_level")]
    pub log_level: String,
    #[serde(rename = "log_file")]
    pub log_file: String,
    #[serde(rename = "platform_base_url")]
    pub platform_base_url: String,
    #[serde(
        rename = "cors_allow_all_origins",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cors_allow_all_origins: Option<Option<bool>>,
    #[serde(
        rename = "zombie_execution_threshold_seconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub zombie_execution_threshold_seconds: Option<Option<i32>>,
}

impl PlatformConfigOut {
    /// Safe-to-expose conf.json values.
    pub fn new(
        pipelit_dir: String,
        sandbox_mode: String,
        database_url: String,
        redis_url: String,
        log_level: String,
        log_file: String,
        platform_base_url: String,
    ) -> PlatformConfigOut {
        PlatformConfigOut {
            pipelit_dir,
            sandbox_mode,
            database_url,
            redis_url,
            log_level,
            log_file,
            platform_base_url,
            cors_allow_all_origins: None,
            zombie_execution_threshold_seconds: None,
        }
    }
}
