/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledJobCreate {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "workflow_id")]
    pub workflow_id: i32,
    #[serde(rename = "trigger_node_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_node_id: Option<Option<String>>,
    #[serde(rename = "interval_seconds")]
    pub interval_seconds: i32,
    #[serde(rename = "total_repeats", skip_serializing_if = "Option::is_none")]
    pub total_repeats: Option<i32>,
    #[serde(rename = "max_retries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
    #[serde(rename = "timeout_seconds", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<i32>,
    #[serde(rename = "trigger_payload", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_payload: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl ScheduledJobCreate {
    pub fn new(name: String, workflow_id: i32, interval_seconds: i32) -> ScheduledJobCreate {
        ScheduledJobCreate {
            name,
            description: None,
            workflow_id,
            trigger_node_id: None,
            interval_seconds,
            total_repeats: None,
            max_retries: None,
            timeout_seconds: None,
            trigger_payload: None,
        }
    }
}

