/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleJobInfo {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "run_count")]
    pub run_count: i32,
    #[serde(rename = "error_count")]
    pub error_count: i32,
    #[serde(rename = "current_repeat")]
    pub current_repeat: i32,
    #[serde(rename = "current_retry")]
    pub current_retry: i32,
    #[serde(rename = "total_repeats")]
    pub total_repeats: i32,
    #[serde(rename = "max_retries")]
    pub max_retries: i32,
    #[serde(rename = "timeout_seconds")]
    pub timeout_seconds: i32,
    #[serde(rename = "interval_seconds")]
    pub interval_seconds: i32,
    #[serde(rename = "last_run_at", deserialize_with = "Option::deserialize")]
    pub last_run_at: Option<String>,
    #[serde(rename = "next_run_at", deserialize_with = "Option::deserialize")]
    pub next_run_at: Option<String>,
    #[serde(rename = "last_error", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<String>>,
}

impl ScheduleJobInfo {
    pub fn new(
        id: String,
        status: String,
        run_count: i32,
        error_count: i32,
        current_repeat: i32,
        current_retry: i32,
        total_repeats: i32,
        max_retries: i32,
        timeout_seconds: i32,
        interval_seconds: i32,
        last_run_at: Option<String>,
        next_run_at: Option<String>,
    ) -> ScheduleJobInfo {
        ScheduleJobInfo {
            id,
            status,
            run_count,
            error_count,
            current_repeat,
            current_retry,
            total_repeats,
            max_retries,
            timeout_seconds,
            interval_seconds,
            last_run_at,
            next_run_at,
            last_error: None,
            created_at: None,
        }
    }
}
