/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledJobOut {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "workflow_id")]
    pub workflow_id: i32,
    #[serde(rename = "trigger_node_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_node_id: Option<Option<String>>,
    #[serde(rename = "user_profile_id")]
    pub user_profile_id: i32,
    #[serde(rename = "interval_seconds")]
    pub interval_seconds: i32,
    #[serde(rename = "total_repeats", skip_serializing_if = "Option::is_none")]
    pub total_repeats: Option<i32>,
    #[serde(rename = "max_retries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
    #[serde(rename = "timeout_seconds", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<i32>,
    #[serde(rename = "trigger_payload", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trigger_payload: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "current_repeat", skip_serializing_if = "Option::is_none")]
    pub current_repeat: Option<i32>,
    #[serde(rename = "current_retry", skip_serializing_if = "Option::is_none")]
    pub current_retry: Option<i32>,
    #[serde(rename = "last_run_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_run_at: Option<Option<String>>,
    #[serde(rename = "next_run_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_run_at: Option<Option<String>>,
    #[serde(rename = "run_count", skip_serializing_if = "Option::is_none")]
    pub run_count: Option<i32>,
    #[serde(rename = "error_count", skip_serializing_if = "Option::is_none")]
    pub error_count: Option<i32>,
    #[serde(rename = "last_error", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
    #[serde(rename = "created_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<Option<String>>,
    #[serde(rename = "updated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<String>>,
}

impl ScheduledJobOut {
    pub fn new(id: String, name: String, workflow_id: i32, user_profile_id: i32, interval_seconds: i32) -> ScheduledJobOut {
        ScheduledJobOut {
            id,
            name,
            description: None,
            workflow_id,
            trigger_node_id: None,
            user_profile_id,
            interval_seconds,
            total_repeats: None,
            max_retries: None,
            timeout_seconds: None,
            trigger_payload: None,
            status: None,
            current_repeat: None,
            current_retry: None,
            last_run_at: None,
            next_run_at: None,
            run_count: None,
            error_count: None,
            last_error: None,
            created_at: None,
            updated_at: None,
        }
    }
}

