/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduledJobUpdate {
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "interval_seconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub interval_seconds: Option<Option<i32>>,
    #[serde(
        rename = "total_repeats",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub total_repeats: Option<Option<i32>>,
    #[serde(
        rename = "max_retries",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_retries: Option<Option<i32>>,
    #[serde(
        rename = "timeout_seconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub timeout_seconds: Option<Option<i32>>,
    #[serde(
        rename = "trigger_payload",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub trigger_payload: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl ScheduledJobUpdate {
    pub fn new() -> ScheduledJobUpdate {
        ScheduledJobUpdate {
            name: None,
            description: None,
            interval_seconds: None,
            total_repeats: None,
            max_retries: None,
            timeout_seconds: None,
            trigger_payload: None,
        }
    }
}
