/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsResponse {
    #[serde(rename = "config")]
    pub config: Box<models::PlatformConfigOut>,
    #[serde(rename = "environment")]
    pub environment: Box<models::EnvironmentInfo>,
}

impl SettingsResponse {
    pub fn new(
        config: models::PlatformConfigOut,
        environment: models::EnvironmentInfo,
    ) -> SettingsResponse {
        SettingsResponse {
            config: Box::new(config),
            environment: Box::new(environment),
        }
    }
}
