/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsUpdateResponse {
    #[serde(rename = "config")]
    pub config: Box<models::PlatformConfigOut>,
    #[serde(rename = "hot_reloaded")]
    pub hot_reloaded: Vec<String>,
    #[serde(rename = "restart_required")]
    pub restart_required: Vec<String>,
}

impl SettingsUpdateResponse {
    pub fn new(config: models::PlatformConfigOut, hot_reloaded: Vec<String>, restart_required: Vec<String>) -> SettingsUpdateResponse {
        SettingsUpdateResponse {
            config: Box::new(config),
            hot_reloaded,
            restart_required,
        }
    }
}

