/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SettingsUpdate : PATCH body — all fields optional.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SettingsUpdate {
    #[serde(
        rename = "sandbox_mode",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sandbox_mode: Option<Option<String>>,
    #[serde(
        rename = "database_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub database_url: Option<Option<String>>,
    #[serde(
        rename = "redis_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub redis_url: Option<Option<String>>,
    #[serde(
        rename = "log_level",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub log_level: Option<Option<LogLevel>>,
    #[serde(
        rename = "log_file",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub log_file: Option<Option<String>>,
    #[serde(
        rename = "platform_base_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub platform_base_url: Option<Option<String>>,
    #[serde(
        rename = "cors_allow_all_origins",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub cors_allow_all_origins: Option<Option<bool>>,
    #[serde(
        rename = "zombie_execution_threshold_seconds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub zombie_execution_threshold_seconds: Option<Option<i32>>,
}

impl SettingsUpdate {
    /// PATCH body — all fields optional.
    pub fn new() -> SettingsUpdate {
        SettingsUpdate {
            sandbox_mode: None,
            database_url: None,
            redis_url: None,
            log_level: None,
            log_file: None,
            platform_base_url: None,
            cors_allow_all_origins: None,
            zombie_execution_threshold_seconds: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LogLevel {
    #[serde(rename = "DEBUG")]
    Debug,
    #[serde(rename = "INFO")]
    Info,
    #[serde(rename = "WARNING")]
    Warning,
    #[serde(rename = "ERROR")]
    Error,
    #[serde(rename = "CRITICAL")]
    Critical,
}

impl Default for LogLevel {
    fn default() -> LogLevel {
        Self::Debug
    }
}
