/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ShellToolInfo {
    #[serde(rename = "available")]
    pub available: bool,
    #[serde(rename = "tier")]
    pub tier: i32,
}

impl ShellToolInfo {
    pub fn new(available: bool, tier: i32) -> ShellToolInfo {
        ShellToolInfo {
            available,
            tier,
        }
    }
}

