/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskOut {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "epic_id")]
    pub epic_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "created_by_node_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created_by_node_id: Option<Option<String>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "workflow_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<Option<i32>>,
    #[serde(rename = "workflow_slug", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub workflow_slug: Option<Option<String>>,
    #[serde(rename = "execution_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<Option<String>>,
    #[serde(rename = "workflow_source", skip_serializing_if = "Option::is_none")]
    pub workflow_source: Option<String>,
    #[serde(rename = "depends_on", skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    #[serde(rename = "requirements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub requirements: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "estimated_tokens", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub estimated_tokens: Option<Option<i32>>,
    #[serde(rename = "actual_tokens", skip_serializing_if = "Option::is_none")]
    pub actual_tokens: Option<i32>,
    #[serde(rename = "actual_usd", skip_serializing_if = "Option::is_none")]
    pub actual_usd: Option<f64>,
    #[serde(rename = "llm_calls", skip_serializing_if = "Option::is_none")]
    pub llm_calls: Option<i32>,
    #[serde(rename = "tool_invocations", skip_serializing_if = "Option::is_none")]
    pub tool_invocations: Option<i32>,
    #[serde(rename = "duration_ms", skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i32>,
    #[serde(rename = "created_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<Option<String>>,
    #[serde(rename = "updated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<String>>,
    #[serde(rename = "started_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<Option<String>>,
    #[serde(rename = "completed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<Option<String>>,
    #[serde(rename = "result_summary", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub result_summary: Option<Option<String>>,
    #[serde(rename = "error_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    #[serde(rename = "retry_count", skip_serializing_if = "Option::is_none")]
    pub retry_count: Option<i32>,
    #[serde(rename = "max_retries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Vec<serde_json::Value>>,
}

impl TaskOut {
    pub fn new(id: String, epic_id: String, title: String) -> TaskOut {
        TaskOut {
            id,
            epic_id,
            title,
            description: None,
            tags: None,
            created_by_node_id: None,
            status: None,
            priority: None,
            workflow_id: None,
            workflow_slug: None,
            execution_id: None,
            workflow_source: None,
            depends_on: None,
            requirements: None,
            estimated_tokens: None,
            actual_tokens: None,
            actual_usd: None,
            llm_calls: None,
            tool_invocations: None,
            duration_ms: None,
            created_at: None,
            updated_at: None,
            started_at: None,
            completed_at: None,
            result_summary: None,
            error_message: None,
            retry_count: None,
            max_retries: None,
            notes: None,
        }
    }
}

