/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaskCreate {
    #[serde(rename = "epic_id")]
    pub epic_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "depends_on", skip_serializing_if = "Option::is_none")]
    pub depends_on: Option<Vec<String>>,
    #[serde(rename = "priority", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub priority: Option<Option<i32>>,
    #[serde(rename = "workflow_slug", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub workflow_slug: Option<Option<String>>,
    #[serde(rename = "estimated_tokens", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub estimated_tokens: Option<Option<i32>>,
    #[serde(rename = "max_retries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
    #[serde(rename = "requirements", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub requirements: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl TaskCreate {
    pub fn new(epic_id: String, title: String) -> TaskCreate {
        TaskCreate {
            epic_id,
            title,
            description: None,
            tags: None,
            depends_on: None,
            priority: None,
            workflow_slug: None,
            estimated_tokens: None,
            max_retries: None,
            requirements: None,
        }
    }
}

