/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenResponse {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "requires_mfa", skip_serializing_if = "Option::is_none")]
    pub requires_mfa: Option<bool>,
}

impl TokenResponse {
    pub fn new(key: String) -> TokenResponse {
        TokenResponse {
            key,
            requires_mfa: None,
        }
    }
}

