/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserOut {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "first_name")]
    pub first_name: String,
    #[serde(rename = "last_name")]
    pub last_name: String,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "mfa_enabled")]
    pub mfa_enabled: bool,
    #[serde(rename = "key_count", skip_serializing_if = "Option::is_none")]
    pub key_count: Option<i32>,
}

impl UserOut {
    pub fn new(
        id: i32,
        username: String,
        role: Role,
        first_name: String,
        last_name: String,
        created_at: String,
        mfa_enabled: bool,
    ) -> UserOut {
        UserOut {
            id,
            username,
            role,
            first_name,
            last_name,
            created_at,
            mfa_enabled,
            key_count: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "normal")]
    Normal,
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}
