/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserListOut {
    #[serde(rename = "users")]
    pub users: Vec<models::UserOut>,
    #[serde(rename = "total")]
    pub total: i32,
}

impl UserListOut {
    pub fn new(users: Vec<models::UserOut>, total: i32) -> UserListOut {
        UserListOut {
            users,
            total,
        }
    }
}

