/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateDslIn {
    #[serde(rename = "yaml_str")]
    pub yaml_str: String,
}

impl ValidateDslIn {
    pub fn new(yaml_str: String) -> ValidateDslIn {
        ValidateDslIn { yaml_str }
    }
}
