/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceUpdate {
    #[serde(rename = "allow_network", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow_network: Option<Option<bool>>,
    #[serde(rename = "env_vars", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub env_vars: Option<Option<Vec<models::WorkspaceEnvVar>>>,
}

impl WorkspaceUpdate {
    pub fn new() -> WorkspaceUpdate {
        WorkspaceUpdate {
            allow_network: None,
            env_vars: None,
        }
    }
}

