/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowOut {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "is_active")]
    pub is_active: bool,
    #[serde(rename = "is_public")]
    pub is_public: bool,
    #[serde(rename = "is_default")]
    pub is_default: bool,
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<Vec<String>>>,
    #[serde(
        rename = "error_handler_workflow_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error_handler_workflow_id: Option<Option<i32>>,
    #[serde(
        rename = "max_execution_seconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_execution_seconds: Option<i32>,
    #[serde(
        rename = "input_schema",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_schema: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(
        rename = "output_schema",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub output_schema: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(rename = "node_count", skip_serializing_if = "Option::is_none")]
    pub node_count: Option<i32>,
    #[serde(rename = "edge_count", skip_serializing_if = "Option::is_none")]
    pub edge_count: Option<i32>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
}

impl WorkflowOut {
    pub fn new(
        id: i32,
        name: String,
        slug: String,
        description: String,
        is_active: bool,
        is_public: bool,
        is_default: bool,
        created_at: String,
        updated_at: String,
    ) -> WorkflowOut {
        WorkflowOut {
            id,
            name,
            slug,
            description,
            is_active,
            is_public,
            is_default,
            tags: None,
            error_handler_workflow_id: None,
            max_execution_seconds: None,
            input_schema: None,
            output_schema: None,
            node_count: None,
            edge_count: None,
            created_at,
            updated_at,
        }
    }
}
