/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceIn {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(
        rename = "path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub path: Option<Option<String>>,
    #[serde(rename = "allow_network", skip_serializing_if = "Option::is_none")]
    pub allow_network: Option<bool>,
    #[serde(
        rename = "env_vars",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub env_vars: Option<Option<Vec<models::WorkspaceEnvVar>>>,
}

impl WorkspaceIn {
    pub fn new(name: String) -> WorkspaceIn {
        WorkspaceIn {
            name,
            path: None,
            allow_network: None,
            env_vars: None,
        }
    }
}
