/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowIn {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "is_active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    #[serde(rename = "is_public", skip_serializing_if = "Option::is_none")]
    pub is_public: Option<bool>,
    #[serde(rename = "is_default", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<Vec<String>>>,
    #[serde(
        rename = "error_handler_workflow_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub error_handler_workflow_id: Option<Option<i32>>,
    #[serde(
        rename = "max_execution_seconds",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_execution_seconds: Option<i32>,
    #[serde(
        rename = "input_schema",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_schema: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    #[serde(
        rename = "output_schema",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub output_schema: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl WorkflowIn {
    pub fn new(name: String, slug: String) -> WorkflowIn {
        WorkflowIn {
            name,
            slug,
            description: None,
            is_active: None,
            is_public: None,
            is_default: None,
            tags: None,
            error_handler_workflow_id: None,
            max_execution_seconds: None,
            input_schema: None,
            output_schema: None,
        }
    }
}
