/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceOut {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "allow_network")]
    pub allow_network: bool,
    #[serde(rename = "env_vars")]
    pub env_vars: Vec<models::WorkspaceEnvVar>,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl WorkspaceOut {
    pub fn new(
        id: i32,
        name: String,
        path: String,
        allow_network: bool,
        env_vars: Vec<models::WorkspaceEnvVar>,
        created_at: String,
    ) -> WorkspaceOut {
        WorkspaceOut {
            id,
            name,
            path,
            allow_network,
            env_vars,
            created_at,
        }
    }
}
