/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkspaceEnvVar {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(
        rename = "value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<Option<String>>,
    #[serde(
        rename = "credential_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub credential_id: Option<Option<i32>>,
    #[serde(
        rename = "credential_field",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub credential_field: Option<Option<String>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Source>,
}

impl WorkspaceEnvVar {
    pub fn new(key: String) -> WorkspaceEnvVar {
        WorkspaceEnvVar {
            key,
            value: None,
            credential_id: None,
            credential_field: None,
            source: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Source {
    #[serde(rename = "raw")]
    Raw,
    #[serde(rename = "credential")]
    Credential,
}

impl Default for Source {
    fn default() -> Source {
        Self::Raw
    }
}
