/*
 * Workflow Platform API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed errors of method [`create_edge_api_v1_workflows_slug_edges_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEdgeApiV1WorkflowsSlugEdgesPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`create_node_api_v1_workflows_slug_nodes_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateNodeApiV1WorkflowsSlugNodesPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_edge_api_v1_workflows_slug_edges_edge_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteEdgeApiV1WorkflowsSlugEdgesEdgeIdDeleteError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`delete_node_api_v1_workflows_slug_nodes_node_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteNodeApiV1WorkflowsSlugNodesNodeIdDeleteError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_edges_api_v1_workflows_slug_edges_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListEdgesApiV1WorkflowsSlugEdgesGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`list_nodes_api_v1_workflows_slug_nodes_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListNodesApiV1WorkflowsSlugNodesGetError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`schedule_pause_api_v1_workflows_slug_nodes_node_id_schedule_pause_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SchedulePauseApiV1WorkflowsSlugNodesNodeIdSchedulePausePostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`schedule_start_api_v1_workflows_slug_nodes_node_id_schedule_start_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScheduleStartApiV1WorkflowsSlugNodesNodeIdScheduleStartPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`schedule_stop_api_v1_workflows_slug_nodes_node_id_schedule_stop_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScheduleStopApiV1WorkflowsSlugNodesNodeIdScheduleStopPostError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_edge_api_v1_workflows_slug_edges_edge_id_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateEdgeApiV1WorkflowsSlugEdgesEdgeIdPatchError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`update_node_api_v1_workflows_slug_nodes_node_id_patch`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum UpdateNodeApiV1WorkflowsSlugNodesNodeIdPatchError {
    Status422(models::HttpValidationError),
    UnknownValue(serde_json::Value),
}

pub async fn create_edge_api_v1_workflows_slug_edges_post(
    configuration: &configuration::Configuration,
    slug: &str,
    edge_in: models::EdgeIn,
) -> Result<models::EdgeOut, Error<CreateEdgeApiV1WorkflowsSlugEdgesPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_body_edge_in = edge_in;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/edges/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_edge_in);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EdgeOut`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EdgeOut`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateEdgeApiV1WorkflowsSlugEdgesPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn create_node_api_v1_workflows_slug_nodes_post(
    configuration: &configuration::Configuration,
    slug: &str,
    node_in: models::NodeIn,
) -> Result<models::NodeOut, Error<CreateNodeApiV1WorkflowsSlugNodesPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_body_node_in = node_in;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/nodes/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_node_in);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodeOut`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodeOut`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CreateNodeApiV1WorkflowsSlugNodesPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn delete_edge_api_v1_workflows_slug_edges_edge_id_delete(
    configuration: &configuration::Configuration,
    slug: &str,
    edge_id: i32,
) -> Result<(), Error<DeleteEdgeApiV1WorkflowsSlugEdgesEdgeIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_path_edge_id = edge_id;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/edges/{edge_id}/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug),
        edge_id = p_path_edge_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteEdgeApiV1WorkflowsSlugEdgesEdgeIdDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn delete_node_api_v1_workflows_slug_nodes_node_id_delete(
    configuration: &configuration::Configuration,
    slug: &str,
    node_id: &str,
) -> Result<(), Error<DeleteNodeApiV1WorkflowsSlugNodesNodeIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_path_node_id = node_id;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/nodes/{node_id}/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug),
        node_id = crate::apis::urlencode(p_path_node_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<DeleteNodeApiV1WorkflowsSlugNodesNodeIdDeleteError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_edges_api_v1_workflows_slug_edges_get(
    configuration: &configuration::Configuration,
    slug: &str,
) -> Result<Vec<models::EdgeOut>, Error<ListEdgesApiV1WorkflowsSlugEdgesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/edges/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::EdgeOut&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::EdgeOut&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListEdgesApiV1WorkflowsSlugEdgesGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn list_nodes_api_v1_workflows_slug_nodes_get(
    configuration: &configuration::Configuration,
    slug: &str,
) -> Result<Vec<models::NodeOut>, Error<ListNodesApiV1WorkflowsSlugNodesGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/nodes/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::NodeOut&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::NodeOut&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ListNodesApiV1WorkflowsSlugNodesGetError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn schedule_pause_api_v1_workflows_slug_nodes_node_id_schedule_pause_post(
    configuration: &configuration::Configuration,
    slug: &str,
    node_id: &str,
) -> Result<models::NodeOut, Error<SchedulePauseApiV1WorkflowsSlugNodesNodeIdSchedulePausePostError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_path_node_id = node_id;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/nodes/{node_id}/schedule/pause/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug),
        node_id = crate::apis::urlencode(p_path_node_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodeOut`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodeOut`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SchedulePauseApiV1WorkflowsSlugNodesNodeIdSchedulePausePostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn schedule_start_api_v1_workflows_slug_nodes_node_id_schedule_start_post(
    configuration: &configuration::Configuration,
    slug: &str,
    node_id: &str,
) -> Result<models::NodeOut, Error<ScheduleStartApiV1WorkflowsSlugNodesNodeIdScheduleStartPostError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_path_node_id = node_id;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/nodes/{node_id}/schedule/start/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug),
        node_id = crate::apis::urlencode(p_path_node_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodeOut`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodeOut`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ScheduleStartApiV1WorkflowsSlugNodesNodeIdScheduleStartPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn schedule_stop_api_v1_workflows_slug_nodes_node_id_schedule_stop_post(
    configuration: &configuration::Configuration,
    slug: &str,
    node_id: &str,
) -> Result<models::NodeOut, Error<ScheduleStopApiV1WorkflowsSlugNodesNodeIdScheduleStopPostError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_path_node_id = node_id;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/nodes/{node_id}/schedule/stop/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug),
        node_id = crate::apis::urlencode(p_path_node_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodeOut`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodeOut`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ScheduleStopApiV1WorkflowsSlugNodesNodeIdScheduleStopPostError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn update_edge_api_v1_workflows_slug_edges_edge_id_patch(
    configuration: &configuration::Configuration,
    slug: &str,
    edge_id: i32,
    edge_update: models::EdgeUpdate,
) -> Result<models::EdgeOut, Error<UpdateEdgeApiV1WorkflowsSlugEdgesEdgeIdPatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_path_edge_id = edge_id;
    let p_body_edge_update = edge_update;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/edges/{edge_id}/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug),
        edge_id = p_path_edge_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_edge_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EdgeOut`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EdgeOut`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateEdgeApiV1WorkflowsSlugEdgesEdgeIdPatchError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn update_node_api_v1_workflows_slug_nodes_node_id_patch(
    configuration: &configuration::Configuration,
    slug: &str,
    node_id: &str,
    node_update: models::NodeUpdate,
) -> Result<models::NodeOut, Error<UpdateNodeApiV1WorkflowsSlugNodesNodeIdPatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_slug = slug;
    let p_path_node_id = node_id;
    let p_body_node_update = node_update;

    let uri_str = format!(
        "{}/api/v1/workflows/{slug}/nodes/{node_id}/",
        configuration.base_path,
        slug = crate::apis::urlencode(p_path_slug),
        node_id = crate::apis::urlencode(p_path_node_id)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref token) = configuration.bearer_access_token {
        req_builder = req_builder.bearer_auth(token.to_owned());
    };
    req_builder = req_builder.json(&p_body_node_update);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::NodeOut`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::NodeOut`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<UpdateNodeApiV1WorkflowsSlugNodesNodeIdPatchError> =
            serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
