use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::{Context, Result};
use serde::Serialize;

use super::prompts::UserInputs;
use super::tokens::SharedTokens;
use crate::output;

#[derive(Serialize)]
struct GatewayConfig {
    gateway: GatewaySection,
    backends: HashMap<String, BackendEntry>,
    auth: AuthSection,
    credentials: HashMap<String, CredentialEntry>,
}

#[derive(Serialize)]
struct GatewaySection {
    listen: String,
    admin_token: String,
    default_backend: String,
    adapters_dir: String,
    adapter_port_range: [u16; 2],
}

#[derive(Serialize)]
struct BackendEntry {
    protocol: String,
    inbound_url: String,
    token: String,
    active: bool,
}

#[derive(Serialize)]
struct AuthSection {
    send_token: String,
}

#[derive(Serialize)]
struct CredentialEntry {
    adapter: String,
    backend: String,
    token: String,
    active: bool,
    route: CredentialRoute,
}

#[derive(Serialize)]
struct CredentialRoute {
    workflow_slug: String,
    trigger_node_id: String,
}

pub struct FixtureOutput {
    pub workflow_slug: String,
    pub trigger_node_id: String,
}

pub fn config_dir() -> Result<PathBuf> {
    let base = dirs::config_dir().context("Could not determine config directory")?;
    Ok(base.join("plit"))
}

pub fn data_dir() -> Result<PathBuf> {
    let base = dirs::data_local_dir().context("Could not determine data directory")?;
    Ok(base.join("plit"))
}

pub fn config_json_path() -> Result<PathBuf> {
    Ok(config_dir()?.join("config.json"))
}

pub fn dot_env_path() -> Result<PathBuf> {
    Ok(config_dir()?.join(".env"))
}

pub fn pipelit_dir() -> Result<PathBuf> {
    Ok(data_dir()?.join("pipelit"))
}

pub fn venv_dir() -> Result<PathBuf> {
    Ok(data_dir()?.join("venv"))
}

pub fn write_dot_env(inputs: &UserInputs, tokens: &SharedTokens) -> Result<()> {
    let cfg_dir = config_dir()?;
    std::fs::create_dir_all(&cfg_dir)
        .with_context(|| format!("Failed to create config directory: {}", cfg_dir.display()))?;

    let data = data_dir()?;
    let db_path = data.join("pipelit.db");
    let secret_key = uuid::Uuid::new_v4().to_string();

    let content = format!(
        "\
# Pipelit environment — generated by plit init
DATABASE_URL=sqlite:///{db_path}
SECRET_KEY={secret_key}
DEBUG=false
ALLOWED_HOSTS=localhost,127.0.0.1

# Gateway integration
GATEWAY_ENABLED=true
GATEWAY_URL=http://localhost:{gw_port}
GATEWAY_ADMIN_TOKEN={admin_token}
GATEWAY_SEND_TOKEN={send_token}
GATEWAY_INBOUND_TOKEN={inbound_token}
",
        db_path = db_path.display(),
        secret_key = secret_key,
        gw_port = inputs.gateway_port,
        admin_token = tokens.admin_token,
        send_token = tokens.send_token,
        inbound_token = tokens.inbound_token,
    );

    let path = dot_env_path()?;
    std::fs::write(&path, &content)
        .with_context(|| format!("Failed to write {}", path.display()))?;
    restrict_permissions(&path)?;

    output::status(&format!("  ✓ Wrote {}", path.display()));
    Ok(())
}

pub fn write_gateway_config(
    inputs: &UserInputs,
    tokens: &SharedTokens,
    fixture: &FixtureOutput,
) -> Result<()> {
    let cfg_dir = config_dir()?;
    std::fs::create_dir_all(&cfg_dir)
        .with_context(|| format!("Failed to create config directory: {}", cfg_dir.display()))?;

    let data = data_dir()?;
    let adapters_dir = data.join("pipelit").join("adapters");
    let credential_token = uuid::Uuid::new_v4().to_string();

    let mut backends = HashMap::new();
    backends.insert(
        "pipelit".to_string(),
        BackendEntry {
            protocol: "pipelit".to_string(),
            inbound_url: format!("http://localhost:{}/api/v1/inbound", inputs.pipelit_port),
            token: tokens.inbound_token.clone(),
            active: true,
        },
    );

    let mut credentials = HashMap::new();
    credentials.insert(
        "default_agent".to_string(),
        CredentialEntry {
            adapter: "generic".to_string(),
            backend: "pipelit".to_string(),
            token: credential_token.clone(),
            active: true,
            route: CredentialRoute {
                workflow_slug: fixture.workflow_slug.clone(),
                trigger_node_id: fixture.trigger_node_id.clone(),
            },
        },
    );

    let config = GatewayConfig {
        gateway: GatewaySection {
            listen: format!("127.0.0.1:{}", inputs.gateway_port),
            admin_token: tokens.admin_token.clone(),
            default_backend: "pipelit".to_string(),
            adapters_dir: adapters_dir.to_string_lossy().to_string(),
            adapter_port_range: [9000, 9100],
        },
        backends,
        auth: AuthSection {
            send_token: tokens.send_token.clone(),
        },
        credentials,
    };

    let path = config_json_path()?;
    let json =
        serde_json::to_string_pretty(&config).context("Failed to serialize gateway config")?;
    std::fs::write(&path, &json).with_context(|| format!("Failed to write {}", path.display()))?;
    restrict_permissions(&path)?;

    output::status(&format!("  ✓ Wrote {}", path.display()));
    Ok(())
}

#[cfg(unix)]
fn restrict_permissions(path: &std::path::Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
        .with_context(|| format!("Failed to set permissions on {}", path.display()))
}

#[cfg(not(unix))]
fn restrict_permissions(_path: &std::path::Path) -> Result<()> {
    Ok(())
}
